spring.application.name=aspectOrientedProgram
spring.datasource.url = jdbc:postgresql://localhost:5432/StudentDatabase
spring.datasource.username = postgres
spring.datasource.password = 8247
spring.datasource.driver-class = org.postgresql.driver

# Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
